<<<<<<< HEAD
name:  test-case
=======
name: trendyol-case
>>>>>>> 5aca0f9 (notebook only)

channels:
  - conda-forge

dependencies:
<<<<<<< HEAD
  - pip
  - pip:
    - ploomber
    - pandas
    - scikit-learn

=======
  - python=3.10
  - pip
  - pip:
    - pandas
    - numpy
    - scikit-learn
    - seaborn
    - matplotlib
    - xgboost
    - openpyxl
    - ipykernel
    - category-encoders
    - yellowbrick
    - tqdm
    - nltk
>>>>>>> 5aca0f9 (notebook only)
